project:
  type: website
  render:
    - index.qmd
    - R/artist_series.qmd
    - R/album_series.qmd
    - R/recording_series.qmd
    - R/about.qmd

website:
  title: "MusicBrainz data: a focus on drummers"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Series"
        menu:
          - R/artist_series.qmd 
          - R/album_series.qmd
          - R/recording_series.qmd
      - R/about.qmd

format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true
