project:
  type: website
  render:
    - index.qmd
    - R/artist_series.qmd
    - R/album_series.qmd
    - R/recording_series.qmd
    - R/about.qmd

website:
  title: "MusicBrainz data: a focus on drummers"
  favicon: images/favicon.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Series"
        menu:
          - text: "Artists"
            href: R/artist_series.qmd 
          - text: "Albums"
            href: R/album_series.qmd
          - text: "Songs"
            href: R/recording_series.qmd
      - R/about.qmd

format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true

#brand: _brand.yml